### ISSUE TITLE
`crust_node` example returns a port as an endpoint

### ISSUE THREAD

**Issue by Fraser999** [dirvine/crust#61]
When trying to bootstrap to an existing "server" crust node by doing 

    target\debug\examples\crust_node.exe 5555 -b 5483

I get the following output:

>     Failed to parse bootstrap peer as valid IPv4 or IPv6 address: 5483

This implies that the server is returning a port as an endpoint.

**Comment by maqi** [comment]
when -b option is to be used, the format of peer address shall be like : 0.0.0.0:5483
-b option is actually more like asking the new node to "connect" to peer, so a full IPv4 or IPv6 address is expected.
This has been shown in the usage part in the code : Line 58 - Line 67
