### ISSUE TITLE
`crust_node` example output and usage comments are unhelpful.

### ISSUE THREAD

**Issue by Fraser999** [dirvine/crust#65]
The comments in crust_node.rs state e.g.

>     // starting second node : cargo run --example crust_node -- 5883 -b 0.0.0.0:5983

The output from running a crust_node in server mode by doing

    target\debug\examples\crust_node.exe -o 6666

yields the following output:

>     Connection manager now listening on TCP socket 0.0.0.0:6666

However, when connecting another node, we need to use the server's actual IP address, not 0.0.0.0.

**Comment by Fraser999** [comment]
Using 0.0.0.0 doesn't seem to be an issue on OS X, and probably isn't a problem on Linux either.

**Comment by dirvine** [comment]
This means all IP addresses, I think with beacon on a LAN we will be OK, but the node should find it's own IP address for those who connect to it as well. We perhaps require the sniffing logic from rudp and the IANA addresses for checking external IP.

**Comment by maqi** [comment]
using 0.0.0.0 or 127.0.0.1 or the actually ip address depends on what has been printed out in "add new node <address>", which might be OS dependent.
